version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.1
    steps:
      - checkout
      - run: find .
      - run: dotnet restore -p:JobId=.${CIRCLE_BUILD_NUM}
      - run: dotnet build -p:JobId=.${CIRCLE_BUILD_NUM}
      - run: dotnet test --no-build -p:JobId=.${CIRCLE_BUILD_NUM}
      - run: dotnet pack RigidFluency/RigidFluency.csproj --configuration Release -p:JobId=.${CIRCLE_BUILD_NUM}
      - run: dotnet nuget push RigidFluency/bin/Release/*.nupkg -k ${NugetApiKey} -s https://api.nuget.org/v3/index.json